INSERT INTO coffee (blend_name, origin, variety, notes, intensifier, price)
VALUES
('Good-morning Symphony','Dipilto, Nicaragua','Kona','crisp, coating, concord grape, fresh wood, maple syrup','astringent',23.7),
('KrebStar Mug','Central Valley, Costa Rica','Yellow Bourbon','mild, tea-like, pineapple, barley, musty','delicate',40.0),
('KrebStar Volcano','Chiriqui, Panama','Dega','dense, juicy, papaya, cinnamon, mandarin','complex',34.5),
('Veranda Cake','Cerrado, Brazil','Dega','soft, syrupy, maple syrup, sweet pea, dill','balanced',30.2),
('Pumpkin-spice Solstice','Agalta, Honduras','Pacamara','sharp, big, nutmeg, carbon, nutmeg','delicate',32.6),
('Seattle Nuts','Jalapa, Nicaragua','Red Bourbon','crisp, chewy, granola, leathery, liquorice','dull',27.2),
('Seattle Star','Lintong, Sumatra','Bourbon','vibrant, watery, olive, cocoa powder, mango','muted',15.8),
('Seattle Light','Fraijanes, Guatemala','Java','muted, watery, marshmallow, cocoa powder, meyer lemon','unbalanced',36.4),
('Kreb-Full-o Treat','Brunca, Costa Rica','Kaffa','dense, round, peach, orange creamsicle, granola','dense',22.5),
('Green Level','Mattari, Yemen','Liberica','dense, juicy, cinnamon, cherry, pineapple','lingering',16.3),
('Strong Cake','Raimi, Yemen','Pacamara','juicy, creamy, raisin, baggy, coconut','dry',34.8),
('Major America','Hirazi, Yemen','Villalobos','dull, creamy, tomato, meyer lemon, walnut','pointed',36.5),
('Express Light','Cacahuatique, El Salvador','Mokka','sharp, watery, hibiscus, red currant, lychee','tart',35.8),
('Brooklyn Cup','Matagalpa, Nicaragua','Blue Mountain','juicy, creamy, orange blossom, cedar, clove','bright',25.6),
('Morning ','Sidama, Ethiopia','Red Bourbon','crisp, round, lychee, watermelon, watermelon','dry',12.2),
('Chocolate Forrester','Lintong, Sumatra','Ennarea','wild, creamy, green apple, baggy, nutella','tart',31.5),
('Kreb-Full-o Select','Orosi, Costa Rica','Bourbon','pointed, silky, mango, hay, black cherry','unbalanced',27.0),
('Street Cup','Manjarabad, India','S795','tart, big, snow pea, nutella, black currant','mild',24.0),
('American Treat','Kayanza, Burundi','Obata','mild, watery, olive, milk chocolate, dates','dirty',25.7),
('Regs Javas Java','Apaneca-Ilamatepec, El Salvador','Gimma','unbalanced, smooth, lemon, rye, tomato','astringent',35.1),
('Express Select','Volcan, Panama','Typica','sharp, tea-like, cantaloupe, nutella, black currant','rounded',16.9),
('Street Mug','Northern Region, Arusha, Tanzania','Colombia','crisp, full, green grape, plum, hay','pointed',37.0),
('Café Mug','Northern Region, Kilimanjaro, Tanzania','Dilla','wild, tea-like, white pepper, cherry, rose hips','dry',11.5),
('Cascara Select','Cerrado, Brazil','Catimors','rounded, chewy, cream, medicinal, fresh wood','quick',17.2),
('Blue Enlightenment','Southern Region, Mbinga, Tanzania','Pacas','rounded, tea-like, concord grape, white grape, bakers chocolate','balanced',23.1),
('Melty ','Cacahuatique, El Salvador','Agaro','dry, big, dates, cherry, lemongrass','pointed',30.9),
('The Level','Lintong, Sumatra','Colombia','vibrant, round, green pepper, tamarind, clementine','clean',12.9),
('Kreb-Full-o Delight','Kibale, Uganda','Dega','dull, big, black-tea, hibiscus, green-tea','clean',28.3),
('Major ','Northern Region, Kilimanjaro, Tanzania','Red Bourbon','rounded, round, almond, red apple, green-tea','clean',26.9),
('KrebStar Volcano','Sul Minas, Brazil','Villalobos','clean, velvety, green-tea, mandarin, hops','juicy',15.4),
('Jacked Cake','Antigua, Guatemala','Gesha','unbalanced, big, lychee, lemongrass, raisin','dry',34.8),
('Seattle Volcano','Tapanuli, Sumatra','Pacamara','bright, round, tamarind, white grape, squash','structured',39.1),
('Captains Coffees Coffee','Gimbi, Ethiopia','SL34','mild, round, white grape, pineapple, butter','mild',26.8),
('Major Java','Apaneca-Ilamatepec, El Salvador','S795','unbalanced, watery, raisin, concord grape, honeysuckle','dirty',14.4),
('Dark Equinox','Copan, Honduras','Liberica','unbalanced, coating, medicinal, pineapple, grassy','wild',25.3),
('Kreb-Full-o Blend','Sul Minas, Brazil','Sumatara','dense, full, cinnamon, mint, squash','pointed',30.5),
('Thanksgiving Forrester','Mogiana, Brazil','Catuai','soft, syrupy, lime, rye, olive','deep',28.7),
('Hello Cowboy','Bugisu, Uganda','Kona','faint, tea-like, walnut, musty, passion fruit','juicy',30.5),
('Cascara Utopia','Machakos, Kenya','Colombia','mild, creamy, banana, cantaloupe, rye','muted',28.3),
('Wake-up Been','Nueva Segovia, Nicaragua','Dega','dull, big, squash, vanilla, tomato','faint',30.5),
('Blacktop Breaker','Sanani, Yemenani, Yemen','Pacas','structured, watery, sugar cane, butter, white pepper','faint',37.0),
('Street Breaker','Manjarabad, India','Kent','crisp, syrupy, maple syrup, green grape, molasses','soft',21.5),
('Huggy Solstice','Ojimmah, Ethiopia','Geisha','vibrant, chewy, grassy, almond, soy sauce','rounded',11.7),
('Express Cake','Brahmaputra, India','SL34','vibrant, juicy, peanut, cashew, black pepper','quick',16.9),
('The ','Cerrado, Brazil','Typica','mild, full, hops, raisin, medicinal','unbalanced',34.8),
('The Captains Beens Been','Sul Minas, Brazil','Villalobos','dirty, juicy, honeydew, black currant, fresh bread','vibrant',11.0),
('Morning Choice','Kayanza, Burundi','Tafari-Kela','quick, juicy, grassy, jasmine, green pepper','structured',28.0),
('Veranda Light','Tapanuli, Sumatra','Catimors','juicy, silky, cranberry, lemon, strawberry','dull',26.8),
('Pumpkin-spice Mug','Raimi, Yemen','Agaro','bright, velvety, watermelon, orange blossom, butter','dirty',34.6),
('Seattle Delight','Kayanza, Burundi','S.4','structured, syrupy, grapefruit, marzipan, red currant','tart',16.0),
('Bluebery Light','Lintong, Sumatra','Colombia','dense, juicy, barley, green grape, walnut','mild',34.4),
('Kreb-Full-o Cake','Coorg, India','Kona','mild, coating, dates, nougat, star fruit','clean',24.4),
('Dark Extract','Bungoma, Kenya','Kona','dull, silky, magnolia, star fruit, plum','mild',26.2),
('Street Look','Jalapa, Nicaragua','Caturra','juicy, chewy, tobacco, squash, baggy','clean',39.1),
('Heart ','Nueva Segovia, Nicaragua','Pacamara','rounded, syrupy, wheat, vanilla, nougat','vibrant',29.3),
('The Look','Chiriqui, Panama','Agaro','tart, full, red currant, mango, wheat','pointed',23.5),
('American Look','Montecillos, Honduras','Kona','complex, round, cherry, pecan, cedar','delicate',38.2),
('Red Cake','Mattari, Yemen','SL34','lingering, tea-like, olive, butter, carbon','astringent',24.8),
('Red Nuts','Lekempti, Ethiopia','S795','structured, juicy, peach, olive, cedar','clean',24.8),
('American Cup','Kiamba, Kenya','Typica','unbalanced, watery, cherry, butter, vanilla','astringent',19.3),
('Blacktop Star','Kayanza, Burundi','Villalobos','vibrant, coating, cocoa powder, cranberry, soy sauce','astringent',26.6),
('Regs Coffees Coffee','San Luis Potosi, Mexico','Kent','lingering, tea-like, honey, black pepper, baggy','bright',23.9),
('The Captains Cowboys Cowboy','Antioquia, Colombia','San Ramon','vibrant, big, nutmeg, fresh bread, marzipan','clean',16.6),
('Dark Coffee','Central Valley, Costa Rica','Mokka','dirty, watery, red grape, hazelnut, sugar cane','bright',34.6),
('Green Level','Northern Region, Arusha, Tanzania','Pacas','sharp, chewy, magnolia, wheat, red currant','faint',27.5),
('Café Been','Gishamwana Coffee Island, Rwanda','Pacamara','deep, slick, mango, cinnamon, nutella','clean',33.8),
('Morning Treat','Nyeri, Kenya','Obata','delicate, creamy, papaya, cola, pecan','dense',24.7),
('Dark America','Copan, Honduras','Sumatara','pointed, tea-like, red apple, pineapple, red currant','astringent',24.3),
('Captains Delights Delight','Gishamwana Coffee Island, Rwanda','Typica','bright, velvety, plum, green pepper, mango','deep',26.6),
('Blacktop Volcano','Lekempti, Ethiopia','Villa Sarchi','unbalanced, creamy, white pepper, honey, cedar','delicate',36.6),
('Chocolate America','Boyacá, Colombia','Barbuk Sudan','sharp, chewy, graham cracker, corriander, brown sugar','rounded',16.8),
('Red Look','Lekempti, Ethiopia','Red Bourbon','dirty, tea-like, leathery, almond, fresh wood','astringent',31.5),
('Huggy Forrester','Cacahuatique, El Salvador','Typica','pointed, velvety, quakery, mint, rye','bright',15.3),
('Postmodern Extract','Huila, Colombia','Obata','quick, velvety, green grape, star fruit, soil','delicate',33.4),
('Dark America','West Valley, Costa Rica','Pacas','dirty, slick, cashew, peanut, watermelon','quick',32.7),
('Thanksgiving Nuts','Lake Tawar, Sumatra','Kona','faint, chewy, cashew, squash, tomato','sharp',12.9),
('Blacktop Symphony','Kayanza, Burundi','Kona','dense, syrupy, squash, rubber, musty','structured',19.8),
('Dark Mug','Bugisu, Uganda','S.4','clean, slick, green pepper, wheat, brown sugar','clean',36.0),
('Pumpkin-spice Coffee','Nariño, Colombia','S288','dry, juicy, nectarine, black currant, golden raisin','quick',39.6),
('Blacktop Select','Pulneys, India','Dilla','complex, creamy, magnolia, liquorice, cream','tart',21.5),
('Regs Stars Star','Tecapa-Chinameca, El Salvador','Catuai','juicy, smooth, orange blossom, black cherry, blueberry','lingering',40.9),
('Dark Equinox','Kiamba, Kenya','Red Bourbon','faint, smooth, nutmeg, coconut, red currant','astringent',40.3),
('Captains Cowboys Cowboy','Chiriqui, Panama','Colombia','vibrant, coating, fresh bread, white grape, potato defect!','clean',32.8),
('Blue Cowboy','Estelí, Nicaragua','Gesha','quick, watery, white pepper, lychee, strawberry','pointed',39.0),
('Postmodern Delight','Hirazi, Yemen','Yellow Bourbon','unbalanced, big, red apple, nutella, honey','quick',35.1),
('Summer Equinox','Chiriqui, Panama','Ethiopian Heirloom','dry, big, pineapple, lemon, green-tea','unbalanced',26.4),
('The Captains Coffees Coffee','Bugisu, Uganda','SL34','bright, slick, quakery, green grape, plum','dense',15.9),
('Good-morning Level','Puebla, Mexico','Kona','astringent, velvety, lemon verbena, graham cracker, tobacco','wild',33.2),
('Hello Java','Kayanza, Burundi','Villalobos','vibrant, creamy, papaya, white grape, hazelnut','clean',30.4),
('Chocolate Level','Nayarit, Mexico','Gimma','mild, slick, white grape, golden raisin, tomato','dull',19.2),
('Holiday Solstice','Western Region, Bukova, Tanzania','Dilla','dull, smooth, rubber, hazelnut, walnut','dry',13.5),
('Winter Java','Kayanza, Burundi','Dilla','vibrant, silky, apricot, rubber, pineapple','dense',32.2),
('Wake-up Light','Kisii, Kenya','Typica','unbalanced, tea-like, plum, lychee, olive','balanced',33.5),
('Captains Selects Select','Raimi, Yemen','Kaffa','deep, creamy, nutmeg, peanut, milk chocolate','muted',27.2),
('Evening Cup','Lekempti, Ethiopia','Villalobos','dense, round, lavender, almond, lavender','soft',27.0),
('Cascara ','Rulindo, Rwanda','S.4','vibrant, slick, strawberry, honey, lychee','faint',12.5),
('Bluebery Breaker','Western Region, Bukova, Tanzania','S288','deep, watery, barley, black pepper, red currant','vibrant',26.9),
('Heart Look','Kibale, Uganda','Catimors','juicy, watery, sugar cane, white pepper, lavender','pointed',34.0),
('Chocolate Cup','Nayarit, Mexico','Yellow Bourbon','muted, full, squash, white grape, kiwi','muted',37.8),
('Captains Looks Look','Muranga, Kenyaa, Kenya','Kaffa','dry, chewy, cinnamon, cranberry, soy sauce','wild',34.5),
('Winter Java','Meru, Kenya','Pacamara','deep, full, mushroom, red currant, strawberry','complex',38.2),
('Brooklyn Select','Veracruz, Mexico','Gimma','dry, juicy, soy sauce, blueberry, cantaloupe','soft',20.5),
('Morning Forrester','Northern Region, Arusha, Tanzania','Blue Mountain','tart, creamy, green pepper, black cherry, cinnamon','soft',29.5),
('Hello Treat','Tarrazu, Costa Rica','S.4','astringent, chewy, blueberry, meyer lemon, star fruit','delicate',12.7),
('Evening Extract','Central Valley, Costa Rica','Tafari-Kela','unbalanced, silky, tobacco, red apple, graham cracker','lingering',11.2),
('Veranda Cup','Kayanza, Burundi','Dilla','dull, juicy, brown sugar, brown sugar, snow pea','clean',29.4),
('Regs Enlightenments Enlightenment','Boaco, Nicaragua','Agaro','juicy, round, sundried tomato, leathery, tobacco','muted',36.6),
('Bluebery Volcano','Chichontepec, El Salvador','Mokka','rounded, coating, carbon, orange creamsicle, white grape','sharp',27.7),
('Café Nuts','Nyanza, Kenya','S288','vibrant, tea-like, leathery, soil, soil','tart',14.6),
('Chocolate Light','Manjarabad, India','Pink Bourbon','dry, juicy, cedar, cranberry, ginger','tart',35.2),
('Blacktop Mug','Chiriqui, Panama','Villa Sarchi','vibrant, round, cacao nibs, orange, honey','deep',32.9),
('Pumpkin-spice Mug','Nuevo Oriente, Guatemala','Yellow Bourbon','astringent, tea-like, lemonade, strawberry, tamarind','deep',39.8),
('Green Select','Boaco, Nicaragua','Agaro','faint, slick, cacao nibs, fresh wood, marshmallow','sharp',20.7),
('The Breaker','Chiapas, Mexico','Java','quick, round, figs, cocoa powder, mandarin','dull',24.0),
('Spilt Symphony','Granada, Nicaragua','Bourbon','tart, chewy, rose hips, tangerine, honeydew','structured',11.1),
('Heart Pie','Lekempti, Ethiopia','Sarchimor','tart, syrupy, magnolia, orange creamsicle, almond','juicy',31.7),
('The Solstice','Managua, Nicaragua','S.4','clean, watery, banana, pineapple, bittersweet chocolate','juicy',14.9),
('Blue Utopia','Apaneca-Ilamatepec, El Salvador','Pacamara','pointed, coating, rye, vanilla, walnut','astringent',20.8),
('Wake-up Cowboy','Kiamba, Kenya','Pacamara','unbalanced, tea-like, red apple, sugar cane, cedar','wild',29.3),
('Jacked Blend','Aceh, Sumatra','Gimma','structured, watery, lychee, baggy, watermelon','wild',29.0),
('Jacked Choice','Manjarabad, India','S288','tart, syrupy, vanilla, bergamot, white pepper','wild',27.8),
('Veranda Extract','Lake Tawar, Sumatra','Red Bourbon','complex, full, rye, cashew, hazelnut','dull',34.1),
('Blue Forrester','Northern Region, Arusha, Tanzania','Yellow Bourbon','muted, coating, honeysuckle, dates, soil','sharp',17.5),
('Good-morning Forrester','El Balsamo-Quetzaltepec, El Salvador','Geisha','mild, juicy, mango, baggy, smokey','unbalanced',16.3),
('Major Cake','El Balsamo-Quetzaltepec, El Salvador','Bourbon','vibrant, velvety, walnut, cinnamon, tomato','unbalanced',39.2),
('Express Delight','Puebla, Mexico','Pink Bourbon','wild, round, lime, sage, ginger','juicy',16.2),
('Express Been','Nyeri, Kenya','Geisha','dry, big, liquorice, mushroom, blueberry','vibrant',33.3),
('Wake-up ','Mbeya Region, Tanzania','Obata','faint, syrupy, magnolia, cocoa powder, fresh bread','balanced',26.2),
('Café Bean','Volcan, Panama','Catimors','pointed, big, vanilla, golden raisin, brown sugar','crisp',37.2),
('Winter Solstice','Kibale, Uganda','San Ramon','rounded, creamy, papaya, leafy greens, star fruit','balanced',35.7),
('Summer Level','San Marcos, Guatemala','S288','dry, round, sage, raisin, mandarin','deep',19.1),
('Goodbye Light','Southern Region, Mbinga, Tanzania','Java','juicy, velvety, honeysuckle, mint, hops','wild',36.3),
('Wake-up Treat','Chichontepec, El Salvador','Gesha','dry, juicy, grapefruit, hazelnut, mint','dirty',23.4),
('Wake-up Level','Acatenango, Guatemala','S.4','tart, coating, marshmallow, white pepper, hibiscus','balanced',37.0),
('Joe Coffee','Mount Elgon, Uganda','Blue Mountain','soft, chewy, honeydew, lychee, nectarine','bright',14.7),
('Melty Equinox','Sanani, Yemenani, Yemen','Ethiopian Heirloom','unbalanced, tea-like, raisin, cranberry, baggy','structured',11.2),
('Joe Town','Chichontepec, El Salvador','Caturra','mild, watery, clementine, cocoa powder, cantaloupe','soft',40.5),
('Thanksgiving Solstice','Sheveroys, India','San Ramon','crisp, tea-like, orange blossom, cacao nibs, figs','tart',36.7),
('Summer Cup','Nueva Segovia, Nicaragua','Sarchimor','tart, chewy, corriander, lavender, graham cracker','dense',18.2),
('Spilt Treat','Sanani, Yemenani, Yemen','Catimors','crisp, syrupy, tobacco, fresh wood, black currant','unbalanced',25.8),
('Dark Nuts','Western Region, Tarime, Tanzania','Ennarea','dirty, watery, baggy, lime, red apple','tart',36.0),
('Goodbye Been','Gimbi, Ethiopia','SL34','lingering, velvety, star fruit, granola, tomato','structured',38.8),
('Spilt Cowboy','Fraijanes, Guatemala','Gimma','faint, watery, raspberry, white grape, snow pea','crisp',11.8),
('Café Java','Oaxaca, Mexico','Yellow Bourbon','dirty, smooth, quakery, pineapple, soil','quick',30.3),
('Jacked Equinox','Kirinyaga, Kenya','Dilla','delicate, coating, ginger, cranberry, hay','dense',20.4),
('Winter Pie','Antigua, Guatemala','Geisha','wild, round, sweet pea, potato defect!, nectarine','unbalanced',11.9),
('Street Select','Chichontepec, El Salvador','SL34','vibrant, big, pecan, toast, orange blossom','quick',40.0);
